Step5 -> step6
AlexProkhor/DotNext-Moscow-2020 pull request #5
Opened 2021-03-13 13:01 UTC by AlexProkhor

Step 5 -> step 6.

2021-03-14 08:45 UTC, max-arshinov requested changes

2021-03-14 08:45 UTC, max-arshinov commented on Modules/HightechAngular.Admin/Features/OrderManagement/CompleteOrderAdminCommandHandler.cs
> +            if (result == null)
здесь можно избавить от этой проверки, если в CompleteOrderAdminContext добавить 
[Required]
Order.Disputed

Тогда валидатор не пропустит контекст, если заказ будет в неверном статусе

2021-03-14 08:45 UTC, max-arshinov commented on Modules/HightechAngular.Admin/Features/OrderManagement/PayOrderCommandHandler.cs
> +            var result = input.Order.With((Order.New newOrder) => newOrder.BecomePaid());
аналогично

2021-03-14 08:45 UTC, max-arshinov commented on Modules/HightechAngular.Core/Base/ChangeOrderStateCommandContext.cs
> +        public Order Order { get; }
Вот тут можно не Order, а конкретный state использовать

2021-03-14 08:45 UTC, max-arshinov commented on Modules/HightechAngular.Core/Base/ChangeOrderStateCommandContext.cs
> +        public TState State => null;
Собственно вот тут не null, а With

2021-03-14 08:45 UTC, max-arshinov commented on Modules/HightechAngular.Core/Base/ChangeOrderStateCommandHandler.cs
> +                .MapAsync(x => x.EligibleStatus);
Как работает этот метод понятно?

2021-03-14 08:45 UTC, max-arshinov commented on Modules/HightechAngular.Core/Base/IHasOrderState.cs
> +        T? State { get; }
А тут можно убрать ?, ведь вам нужно, чтобы стейт был

2021-03-14 08:45 UTC, max-arshinov commented on Modules/HightechAngular.Shop/Features/Cart/BaseUpdateProductInCartContext.cs
> +    public class BaseUpdateProductInCartContext<TIn, TOut> :
Придерживайтесь конвенции именования. В проекте используется стандартная для R#/Rider - UpdateProductInCartContextBase

2021-03-21 07:34 UTC, max-arshinov requested changes

2021-03-21 07:34 UTC, max-arshinov commented on Modules/HightechAngular.Shop/Features/MyOrders/DisputeOrderCommandHandler.cs
>              var result = input.Order.With((Order.Shipped newOrder) => newOrder.BecomeDisputed());
А здесь должно было стать input.State.BecomeDisputed()

2021-03-21 07:34 UTC, max-arshinov commented on Modules/HightechAngular.Shop/Features/MyOrders/MyOrdersController.cs
> +        //[HttpPost("CreateNew")]
Удалить закомментированный код

2021-03-21 07:34 UTC, max-arshinov commented on Modules/HightechAngular.Admin/Features/OrderManagement/ShipOrderContext.cs
> +        [Required]
Если добавить TState  в качестве второго generic-параметра класса, то эту строчку можно будет заменить на public ```TState State => Order.As<TState>();```

2021-03-26 16:35 UTC, AlexProkhor commented on Modules/HightechAngular.Admin/Features/OrderManagement/ShipOrderContext.cs
> +        [Required]
Это с 7й ветки подсосало, что бы компилировалось и не конфликтовало я заткнул

2021-03-28 09:26 UTC, merged